name: Reusable workflow example

on:
  push:
    branches:
      - 'feature/**'
  workflow_call:
  workflow_dispatch:


jobs:
  example_job:
    name: Test Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/testaction
